NOT_WAITED = "NOT_WAITED"

NO_COIN_FOR_X_MOVES = "NO_COIN_FOR_X_MOVES"

LOOP = "LOOP"
NO_LOOP = "NO_LOOP"
NO_LOOP_SCORE = "NO_LOOP_SCORE"

HIGH_SCORING_GAME = "HIGH_SCORING_GAME"
PERFECT_COIN_HEAVEN = "PERFECT_COIN_HEAVEN"
LOW_SCORING_GAME = "LOW_SCORING_GAME"

SHORTEST_WAY_COIN = "SHORTEST_WAY_COIN"
NOT_SHORTEST_WAY_COIN = "NOT_SHORTEST_WAY_COIN"
SHORTEST_WAY_CRATE = "SHORTEST_WAY_CRATE"
NOT_SHORTEST_WAY_CRATE = "NOT_SHORTEST_WAY_CRATE"
SHORTEST_WAY_SAFETY = "SHORTEST_WAY_SAFETY"
NOT_SHORTEST_WAY_SAFETY = "NOT_SHORTEST_WAY_SAFETY"
SHORTEST_WAY_TRAP = "SHORTEST_WAY_TRAP"
NOT_SHORTEST_WAY_TRAP = "NOT_SHORTEST_WAY_TRAP"

GOOD_BOMB = "GOOD_BOMB"
BAD_BOMB = "BAD_BOMB"
MISSED_BOMB = "MISSED_BOMB"

STEP_ONE_BOMB = "STEP ONE BOMB"
NOT_STEP_ONE_BOMB = "NOT STEP ONE BOMB"

FIRST = "FIRST"
SECOND = "SECOND"
THIRD = "THIRD"
FOURTH = "FOURTH"

TRAP = "TRAP"
MISSED_TRAP = "MISSED_TRAP"
